// First, deliberately: this populates process.env from a .env file if one
// exists, and everything below reads process.env at module scope.
import { loaded as envFile } from "./admin/load-env.js";
import { createServer } from "node:http";
import { createReadStream, existsSync } from "node:fs";
import { stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { handleInvitation, configStatus, env } from "./api/_lib/send-invitation.js";
import { createAdmin, originFor } from "./admin/routes.js";
import { createSessions } from "./admin/auth.js";
import { createDb, migrate } from "./admin/db.js";
import { createPgStore } from "./admin/store-pg.js";
import { createPgUserStore } from "./admin/users-store-pg.js";
import { createUserStore } from "./admin/users-store.js";
import { applySecrets, clearSecret, ensureSessionSecret, secretStatus, setSecret } from "./admin/secrets.js";
import { materialise, seedAdmins, seedContent, writeThrough } from "./admin/db-bootstrap.js";
import { createPinner } from "./admin/ipfs.js";
import { backfill, listPins, pinDocument, pinStatus } from "./admin/pins.js";
import { setRuntimeConfig } from "./admin/runtime-config.js";
import { createFsStore } from "./admin/store-fs.js";
import { rebuild, lastBuild } from "./admin/rebuild.js";
import {
  durability,
  ensureContentDir,
  mirrorFile,
  persistentSecret,
  syncToWorkingTree
} from "./admin/content-dir.js";
import { contentStatus as adminContentStatus, pgStatus, volumeStatus } from "./admin/content-status.js";
import { randomUUID } from "node:crypto";

/**
 * Production server for the built site.
 *
 * Replaces what vercel.json did declaratively — clean URLs, cache headers —
 * and additionally runs the invitation endpoint in-process, which a purely
 * static host cannot do.
 *
 * No dependencies beyond Node built-ins and resend.
 */

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "_site");
const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || "0.0.0.0";

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".svg": "image/svg+xml",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".mp4": "video/mp4",
  ".pdf": "application/pdf"
};

// Only content-hashed output may be cached hard. /img/ is generated by
// eleventy-img with a hash in every filename; /assets/ is passthrough with
// stable names, so caching it immutably meant a CSS or JS change never
// reached anyone who had visited before.
const IMMUTABLE = /^\/img\//;
const ONE_YEAR = "public, max-age=31536000, immutable";
const REVALIDATE = "public, max-age=0, must-revalidate";

const MAX_BODY_BYTES = 64 * 1024;

/**
 * Where the editable content lives.
 *
 * Postgres when DATABASE_URL is set, which is how production runs: content,
 * admin accounts and service credentials all live there, so the host needs
 * exactly one environment variable and nothing has to be mounted.
 *
 * Without it, a local directory — so a checkout runs with no database.
 */
const PROJECT_ROOT = fileURLToPath(new URL("./", import.meta.url));
const DATABASE_URL = env("DATABASE_URL");
const CONTENT_DIR =
  env("CONTENT_DIR") ||
  (existsSync("/data") ? "/data" : path.join(PROJECT_ROOT, ".content"));

const db = DATABASE_URL ? createDb({ url: DATABASE_URL }) : null;

/**
 * Images are pinned to IPFS as the record of the original. Not the serving
 * path: the build produces responsive derivatives, and serving full-size
 * originals through a gateway would undo that and put a third party in front
 * of every page load.
 */
const pinner = createPinner();

/**
 * A save writes to the store, puts that one file on disk, and rebuilds.
 *
 * Content changes used to be commits, and every commit triggered a redeploy:
 * minutes of lag, everyone signed out, and the in-memory token that made
 * saving work wiped in the process. This is one write and a sub-second build.
 */
const store = db
  ? createPgStore({
      db,
      onWrite: async ({ path: relative, buffer, digest }) => {
        if (!relative.startsWith("src/")) return;
        await writeThrough({ root: PROJECT_ROOT, relative, buffer });
        await rebuild();

        // Deliberately not awaited. The bytes are already durable and the
        // page is already rebuilt; making the editor wait on a third-party
        // upload would add seconds to every save and fail it when Pinata is
        // down. Anything that does not stick is reported and retried.
        void pinDocument(db, pinner, { path: relative, digest, buffer })
          .then((r) => r.failed && console.error(`pin failed for ${relative}: ${r.failed}`))
          .catch((err) => console.error(`pin error for ${relative}:`, err.message));
      }
    })
  : createFsStore({
      dir: CONTENT_DIR,
      onWrite: async ({ path: relative, absolute }) => {
        // Only what Eleventy builds from is copied back. Accounts are read
        // from the store directly, so mirroring them into the checkout would
        // achieve nothing beyond leaving a copy of the hashes on disk.
        if (!relative.startsWith("src/")) return;
        await mirrorFile(absolute, path.join(PROJECT_ROOT, relative));
        await rebuild();
      }
    });

/**
 * Accounts are rows in Postgres when there is one. ADMIN_USERS survives only
 * as a local-development convenience: in production the owner account lives
 * in the database like every other, because a credential in a host dashboard
 * is one nobody can rotate without the host dashboard.
 */
const userStore = db
  ? createPgUserStore({ db })
  : createUserStore({ gh: store, fallbackUsers: env("ADMIN_USERS") });

const admin = createAdmin({
  sessions: createSessions(),
  store,
  userStore,
  secret: env("SESSION_SECRET"),
  credentials: db
    ? {
        list: () => secretStatus(db),
        set: (name, value, by) => setSecret(db, name, value, by),
        clear: (name) => clearSecret(db, name)
      }
    : null,
  ipfs: db
    ? {
        configured: () => pinner.configured(),
        testAuth: () => pinner.testAuth(),
        status: () => pinStatus(db),
        list: () => listPins(db),
        gatewayUrl: (cid) => pinner.gatewayUrl(cid),
        // Never on boot: the first run uploads every image on the site, and a
        // deploy is not the moment to find out how long that takes.
        backfill: (limit) => backfill(db, store, pinner, { limit })
      }
    : null,
  // Say so in the interface when content is not actually persistent. Saving
  // to an unmounted volume looks entirely normal right up until a deploy
  // throws the work away. A database is durable by construction.
  warning: async () => {
    if (db) return null;
    const state = durability({ ...contentBoot, uptimeSeconds: Math.round(process.uptime()) });
    if (state.durable === true) return null;
    if (state.durable === null) {
      return `${CONTENT_DIR} was created during this deploy, so it has not yet proven it persists. Check /api/health after the next restart.`;
    }
    return `${CONTENT_DIR} is not a persistent volume, so anything saved here will be lost on the next deploy. Set DATABASE_URL, or mount a volume there.`;
  }
});

// Filled in by bootstrap(); left empty when the module is merely imported,
// as the tests do, so importing never touches a volume or a database.
let contentBoot = { marker: null, seeded: false };
let dbBoot = null;

/**
 * Bring storage up, then build from it.
 *
 * Order matters. The store is the source of truth, so it is seeded from the
 * shipped checkout only when empty, then written *over* the working tree, and
 * only then does Eleventy run. Building first would render whatever the deploy
 * happened to contain and put that on screen in place of the real content.
 */
async function bootstrap() {
  if (db) {
    const applied = await migrate(db);
    await ensureSessionSecret(db);
    const credentials = await applySecrets(db);
    const content = await seedContent({ db, store, root: PROJECT_ROOT });
    const admins = await seedAdmins({ db, root: PROJECT_ROOT });
    const written = await materialise({ db, store, root: PROJECT_ROOT });
    dbBoot = { applied, credentials, content, admins, written };

    console.log(
      `postgres: ${applied.length ? `migrated ${applied.join(", ")}; ` : ""}` +
        `${content.documents} documents` +
        (content.seeded ? " (seeded from the checkout)" : "") +
        `, ${admins.accounts} account(s)` +
        (admins.seeded ? " (migrated)" : "") +
        `, ${written.written} file(s) written, ` +
        `credentials from db: ${credentials.length ? credentials.join(", ") : "none"}`
    );
  } else {
    contentBoot = await ensureContentDir({ dir: CONTENT_DIR, root: PROJECT_ROOT });
    const copied = await syncToWorkingTree({ dir: CONTENT_DIR, root: PROJECT_ROOT });
    setRuntimeConfig({ SESSION_SECRET: await persistentSecret({ dir: CONTENT_DIR }) });
    console.log(
      `content: ${CONTENT_DIR}` +
        (contentBoot.seeded ? ` (seeded ${contentBoot.marker.seededFiles} files)` : "") +
        `, ${copied} file(s) refreshed`
    );
  }

  // A failed build must not stop the server: the previously built _site is
  // still on disk and still servable, and a broken build is better reported
  // through /api/health than by refusing to start.
  try {
    const built = await rebuild();
    console.log(`built in ${built.ms}ms`);
  } catch (err) {
    console.error("initial build failed, serving the existing _site:", err.message);
  }
}

function send(res, status, body, headers = {}) {
  res.writeHead(status, {
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    ...headers
  });
  res.end(body);
}

function sendJson(res, status, obj) {
  send(res, status, JSON.stringify(obj), { "Content-Type": "application/json; charset=utf-8" });
}

async function resolveFile(urlPath) {
  // Reject traversal before touching the filesystem.
  const decoded = decodeURIComponent(urlPath);
  if (decoded.includes("\0")) return null;
  const target = path.normalize(path.join(ROOT, decoded));
  if (target !== ROOT && !target.startsWith(ROOT + path.sep)) return null;

  const candidates = decoded.endsWith("/")
    ? [path.join(target, "index.html")]
    : [target, target + ".html", path.join(target, "index.html")];

  for (const candidate of candidates) {
    if (candidate !== ROOT && !candidate.startsWith(ROOT + path.sep)) continue;
    try {
      const info = await stat(candidate);
      if (info.isFile()) return { file: candidate, size: info.size, mtime: info.mtime };
    } catch {
      /* try the next candidate */
    }
  }
  return null;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (c) => {
      size += c.length;
      if (size > MAX_BODY_BYTES) {
        reject(new Error("payload too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

async function serveNotFound(res) {
  const custom = await resolveFile("/404.html");
  if (custom) {
    res.writeHead(404, { "Content-Type": MIME[".html"], "Cache-Control": REVALIDATE });
    createReadStream(custom.file).pipe(res);
    return;
  }
  send(res, 404, "Not found", { "Content-Type": MIME[".txt"] });
}

const server = createServer(async (req, res) => {
  let url;
  try {
    url = new URL(req.url, "http://localhost");
  } catch {
    return send(res, 400, "Bad request", { "Content-Type": MIME[".txt"] });
  }
  const pathname = url.pathname;

  // ---- API ----------------------------------------------------------------
  if (pathname === "/api/request-invitation") {
    if (req.method !== "POST") {
      res.setHeader("Allow", "POST");
      return sendJson(res, 405, { error: "Method not allowed." });
    }
    let parsed;
    try {
      parsed = JSON.parse((await readBody(req)) || "{}");
    } catch {
      return sendJson(res, 400, { error: "Could not read that submission." });
    }
    const { status, body } = await handleInvitation(parsed);
    return sendJson(res, status, body);
  }

  // Reports whether config is present, never what it contains. Lets us tell
  // "variables missing" apart from "Resend rejected the send" without
  // reading logs, and without exposing anything secret.
  if (pathname === "/api/health") {
    return sendJson(res, 200, {
      ok: true,
      host: "self",
      uptimeSeconds: Math.round(process.uptime()),
      // Dates the running code. Content is served from _site on disk, so it
      // can be current while the process itself is running older JavaScript —
      // these fields tell the two apart instead of guessing.
      adminMounted: true,
      adminConfigured: Boolean(db) || existsSync(CONTENT_DIR),
      // Whether the database URL arrived at all, and where from. Names and
      // booleans only. Without this, "still on the filesystem" gives no clue
      // whether the variable is missing, misspelled, or in a file nothing read.
      env: {
        DATABASE_URL: Boolean(env("DATABASE_URL")),
        envFile: envFile.file,
        fromEnvFile: envFile.applied,
        shadowedByHost: envFile.skipped,
        databaseCandidates: Object.keys(process.env)
          .filter((k) => /DATABASE|POSTGRES|^PG/i.test(k))
          .sort()
      },
      // Where content is kept, and whether that directory has actually
      // survived a restart. A volume that was never mounted works exactly
      // like one that was, right up until the next deploy erases it, so this
      // is the field to check after configuring the host.
      content: db
        ? { ...(await pgStatus(db)), boot: dbBoot, lastBuild: lastBuild() }
        : {
            backend: "filesystem",
            ...(await volumeStatus(CONTENT_DIR)),
            ...durability({ ...contentBoot, uptimeSeconds: Math.round(process.uptime()) }),
            lastBuild: lastBuild()
          },
      // Which service credentials are configured and where they came from.
      // Names and booleans only.
      credentials: db ? await secretStatus(db) : null,
      ipfs: db
        ? { configured: pinner.configured(), ...(await pinStatus(db)) }
        : { configured: pinner.configured() },
      // What invitation links will be built from, for this exact request.
      // Links were coming out as http://localhost because they used the
      // parse-time placeholder base rather than the request headers.
      requestOrigin: originFor(req),
      forwardedHeaders: {
        host: req.headers.host ?? null,
        "x-forwarded-host": req.headers["x-forwarded-host"] ?? null,
        "x-forwarded-proto": req.headers["x-forwarded-proto"] ?? null
      },
      // The GitHub repository check is no longer part of the save path, so it
      // is only of interest when investigating an export or a migration.
      // Still opt-in: a health endpoint must never wait on a third party.
      ...(url.searchParams.get("github") ? { github: await adminContentStatus() } : {}),
      ...configStatus()
    });
  }

  // ---- admin --------------------------------------------------------------
  if (await admin.handle(req, res, url)) return;

  if (pathname.startsWith("/api/")) return sendJson(res, 404, { error: "Not found." });

  if (req.method !== "GET" && req.method !== "HEAD") {
    res.setHeader("Allow", "GET, HEAD");
    return send(res, 405, "Method not allowed", { "Content-Type": MIME[".txt"] });
  }

  // ---- cleanUrls: /faq.html -> /faq (matches the old vercel.json) ----------
  if (pathname.endsWith(".html")) {
    const clean = pathname.replace(/(\/index)?\.html$/, "") || "/";
    return send(res, 308, "", { Location: clean + url.search });
  }
  // trailingSlash: false
  if (pathname.length > 1 && pathname.endsWith("/")) {
    return send(res, 308, "", { Location: pathname.slice(0, -1) + url.search });
  }

  // ---- static -------------------------------------------------------------
  const found = await resolveFile(pathname);
  if (!found) return serveNotFound(res);

  const ext = path.extname(found.file).toLowerCase();
  const etag = `W/"${found.size}-${found.mtime.getTime()}"`;

  if (req.headers["if-none-match"] === etag) {
    return send(res, 304, "", { ETag: etag });
  }

  const headers = {
    "Content-Type": MIME[ext] || "application/octet-stream",
    "Content-Length": String(found.size),
    "Cache-Control": IMMUTABLE.test(pathname) ? ONE_YEAR : REVALIDATE,
    ETag: etag
  };

  if (req.method === "HEAD") return send(res, 200, "", headers);

  res.writeHead(200, headers);
  createReadStream(found.file).pipe(res);
});

// Only bind a port when run directly, so tests can listen on an ephemeral one.
const isEntryPoint =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isEntryPoint) {
  await bootstrap();

  server.listen(PORT, HOST, () => {
    console.log(`RegSymp serving ${ROOT} on http://${HOST}:${PORT}`);
  });

  for (const signal of ["SIGTERM", "SIGINT"]) {
    process.on(signal, () => {
      console.log(`${signal} received, shutting down`);
      server.close(() => process.exit(0));
    });
  }
}

export { server };
