import { createServer } from "node:http";
import { createReadStream, existsSync } from "node:fs";
import { stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { handleInvitation, configStatus, env } from "./api/_lib/send-invitation.js";
import { createAdmin, originFor } from "./admin/routes.js";
import { createSessions } from "./admin/auth.js";
import { setRuntimeConfig } from "./admin/runtime-config.js";
import { createFsStore } from "./admin/store-fs.js";
import { rebuild, lastBuild } from "./admin/rebuild.js";
import {
  durability,
  ensureContentDir,
  mirrorFile,
  persistentSecret,
  syncToWorkingTree
} from "./admin/content-dir.js";
import { contentStatus as adminContentStatus, volumeStatus } from "./admin/content-status.js";
import { randomUUID } from "node:crypto";

/**
 * Production server for the built site.
 *
 * Replaces what vercel.json did declaratively — clean URLs, cache headers —
 * and additionally runs the invitation endpoint in-process, which a purely
 * static host cannot do.
 *
 * No dependencies beyond Node built-ins and resend.
 */

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "_site");
const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || "0.0.0.0";

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".svg": "image/svg+xml",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".mp4": "video/mp4",
  ".pdf": "application/pdf"
};

// Only content-hashed output may be cached hard. /img/ is generated by
// eleventy-img with a hash in every filename; /assets/ is passthrough with
// stable names, so caching it immutably meant a CSS or JS change never
// reached anyone who had visited before.
const IMMUTABLE = /^\/img\//;
const ONE_YEAR = "public, max-age=31536000, immutable";
const REVALIDATE = "public, max-age=0, must-revalidate";

const MAX_BODY_BYTES = 64 * 1024;

/**
 * Where the editable content lives.
 *
 * A mounted volume in production, a local directory otherwise. `/data` is the
 * conventional mount point, so it is used when it exists; `CONTENT_DIR`
 * overrides. Getting this wrong is not silent — /api/health reports which
 * directory was chosen and whether it has actually survived a restart.
 */
const PROJECT_ROOT = fileURLToPath(new URL("./", import.meta.url));
const CONTENT_DIR =
  env("CONTENT_DIR") ||
  (existsSync("/data") ? "/data" : path.join(PROJECT_ROOT, ".content"));

/**
 * Saving writes to the volume, then copies that one file into the working
 * tree and rebuilds. Content changes used to be commits, which triggered a
 * redeploy: minutes of lag, and everyone signed out when the container was
 * replaced. This is a file write and a sub-second build.
 */
const store = createFsStore({
  dir: CONTENT_DIR,
  onWrite: async ({ path: relative, absolute }) => {
    // Only what Eleventy builds from is copied back. Accounts are read from
    // the volume directly, so mirroring them into the checkout would achieve
    // nothing beyond leaving a stray copy of the password hashes on disk.
    if (!relative.startsWith("src/")) return;
    await mirrorFile(absolute, path.join(PROJECT_ROOT, relative));
    await rebuild();
  }
});

const admin = createAdmin({
  sessions: createSessions(),
  users: env("ADMIN_USERS"),
  store,
  secret: env("SESSION_SECRET"),
  // Say so in the interface when the content directory is not persistent.
  // Saving would otherwise look completely normal right up until a deploy
  // threw the work away.
  warning: async () => {
    const state = durability({ ...contentBoot, uptimeSeconds: Math.round(process.uptime()) });
    if (state.durable === true) return null;
    if (state.durable === null) {
      return `${CONTENT_DIR} was created during this deploy, so it has not yet proven it persists. Check /api/health after the next restart.`;
    }
    return `${CONTENT_DIR} is not a persistent volume, so anything saved here will be lost on the next deploy. Mount a volume there first.`;
  }
});

// Filled in by bootstrap(); left empty when the module is merely imported,
// as the tests do, so importing never touches a volume.
let contentBoot = { marker: null, seeded: false };

/**
 * Bring the content volume up, then build from it.
 *
 * Order matters. The volume is the source of truth, so it is seeded from the
 * shipped checkout only when it is new, then copied *over* the working tree,
 * and only then does Eleventy run. Building first would render whatever the
 * deploy happened to contain and overwrite the real content on screen.
 */
async function bootstrap() {
  contentBoot = await ensureContentDir({ dir: CONTENT_DIR, root: PROJECT_ROOT });
  const copied = await syncToWorkingTree({ dir: CONTENT_DIR, root: PROJECT_ROOT });
  setRuntimeConfig({ SESSION_SECRET: await persistentSecret({ dir: CONTENT_DIR }) });

  console.log(
    `content: ${CONTENT_DIR}` +
      (contentBoot.seeded ? ` (seeded ${contentBoot.marker.seededFiles} files)` : "") +
      `, ${copied} file(s) refreshed`
  );

  // A failed build must not stop the server: the previously built _site is
  // still on disk and still servable, and a broken build is better reported
  // through /api/health than by refusing to start.
  try {
    const built = await rebuild();
    console.log(`built in ${built.ms}ms`);
  } catch (err) {
    console.error("initial build failed, serving the existing _site:", err.message);
  }
}

function send(res, status, body, headers = {}) {
  res.writeHead(status, {
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    ...headers
  });
  res.end(body);
}

function sendJson(res, status, obj) {
  send(res, status, JSON.stringify(obj), { "Content-Type": "application/json; charset=utf-8" });
}

async function resolveFile(urlPath) {
  // Reject traversal before touching the filesystem.
  const decoded = decodeURIComponent(urlPath);
  if (decoded.includes("\0")) return null;
  const target = path.normalize(path.join(ROOT, decoded));
  if (target !== ROOT && !target.startsWith(ROOT + path.sep)) return null;

  const candidates = decoded.endsWith("/")
    ? [path.join(target, "index.html")]
    : [target, target + ".html", path.join(target, "index.html")];

  for (const candidate of candidates) {
    if (candidate !== ROOT && !candidate.startsWith(ROOT + path.sep)) continue;
    try {
      const info = await stat(candidate);
      if (info.isFile()) return { file: candidate, size: info.size, mtime: info.mtime };
    } catch {
      /* try the next candidate */
    }
  }
  return null;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (c) => {
      size += c.length;
      if (size > MAX_BODY_BYTES) {
        reject(new Error("payload too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

async function serveNotFound(res) {
  const custom = await resolveFile("/404.html");
  if (custom) {
    res.writeHead(404, { "Content-Type": MIME[".html"], "Cache-Control": REVALIDATE });
    createReadStream(custom.file).pipe(res);
    return;
  }
  send(res, 404, "Not found", { "Content-Type": MIME[".txt"] });
}

const server = createServer(async (req, res) => {
  let url;
  try {
    url = new URL(req.url, "http://localhost");
  } catch {
    return send(res, 400, "Bad request", { "Content-Type": MIME[".txt"] });
  }
  const pathname = url.pathname;

  // ---- API ----------------------------------------------------------------
  if (pathname === "/api/request-invitation") {
    if (req.method !== "POST") {
      res.setHeader("Allow", "POST");
      return sendJson(res, 405, { error: "Method not allowed." });
    }
    let parsed;
    try {
      parsed = JSON.parse((await readBody(req)) || "{}");
    } catch {
      return sendJson(res, 400, { error: "Could not read that submission." });
    }
    const { status, body } = await handleInvitation(parsed);
    return sendJson(res, status, body);
  }

  // Reports whether config is present, never what it contains. Lets us tell
  // "variables missing" apart from "Resend rejected the send" without
  // reading logs, and without exposing anything secret.
  if (pathname === "/api/health") {
    return sendJson(res, 200, {
      ok: true,
      host: "self",
      uptimeSeconds: Math.round(process.uptime()),
      // Dates the running code. Content is served from _site on disk, so it
      // can be current while the process itself is running older JavaScript —
      // these fields tell the two apart instead of guessing.
      adminMounted: true,
      adminConfigured: existsSync(CONTENT_DIR),
      // Where content is kept, and whether that directory has actually
      // survived a restart. A volume that was never mounted works exactly
      // like one that was, right up until the next deploy erases it, so this
      // is the field to check after configuring the host.
      content: {
        ...(await volumeStatus(CONTENT_DIR)),
        ...durability({ ...contentBoot, uptimeSeconds: Math.round(process.uptime()) }),
        lastBuild: lastBuild()
      },
      // What invitation links will be built from, for this exact request.
      // Links were coming out as http://localhost because they used the
      // parse-time placeholder base rather than the request headers.
      requestOrigin: originFor(req),
      forwardedHeaders: {
        host: req.headers.host ?? null,
        "x-forwarded-host": req.headers["x-forwarded-host"] ?? null,
        "x-forwarded-proto": req.headers["x-forwarded-proto"] ?? null
      },
      // The GitHub repository check is no longer part of the save path, so it
      // is only of interest when investigating an export or a migration.
      // Still opt-in: a health endpoint must never wait on a third party.
      ...(url.searchParams.get("github") ? { github: await adminContentStatus() } : {}),
      ...configStatus()
    });
  }

  // ---- admin --------------------------------------------------------------
  if (await admin.handle(req, res, url)) return;

  if (pathname.startsWith("/api/")) return sendJson(res, 404, { error: "Not found." });

  if (req.method !== "GET" && req.method !== "HEAD") {
    res.setHeader("Allow", "GET, HEAD");
    return send(res, 405, "Method not allowed", { "Content-Type": MIME[".txt"] });
  }

  // ---- cleanUrls: /faq.html -> /faq (matches the old vercel.json) ----------
  if (pathname.endsWith(".html")) {
    const clean = pathname.replace(/(\/index)?\.html$/, "") || "/";
    return send(res, 308, "", { Location: clean + url.search });
  }
  // trailingSlash: false
  if (pathname.length > 1 && pathname.endsWith("/")) {
    return send(res, 308, "", { Location: pathname.slice(0, -1) + url.search });
  }

  // ---- static -------------------------------------------------------------
  const found = await resolveFile(pathname);
  if (!found) return serveNotFound(res);

  const ext = path.extname(found.file).toLowerCase();
  const etag = `W/"${found.size}-${found.mtime.getTime()}"`;

  if (req.headers["if-none-match"] === etag) {
    return send(res, 304, "", { ETag: etag });
  }

  const headers = {
    "Content-Type": MIME[ext] || "application/octet-stream",
    "Content-Length": String(found.size),
    "Cache-Control": IMMUTABLE.test(pathname) ? ONE_YEAR : REVALIDATE,
    ETag: etag
  };

  if (req.method === "HEAD") return send(res, 200, "", headers);

  res.writeHead(200, headers);
  createReadStream(found.file).pipe(res);
});

// Only bind a port when run directly, so tests can listen on an ephemeral one.
const isEntryPoint =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isEntryPoint) {
  await bootstrap();

  server.listen(PORT, HOST, () => {
    console.log(`RegSymp serving ${ROOT} on http://${HOST}:${PORT}`);
  });

  for (const signal of ["SIGTERM", "SIGINT"]) {
    process.on(signal, () => {
      console.log(`${signal} received, shutting down`);
      server.close(() => process.exit(0));
    });
  }
}

export { server };
